### ISSUE TITLE
Создание модулей по пути, в котором встречаются пробелы.

### ISSUE THREAD

**Issue by EvgenyIv96** [yurapriv/gener#2]
Сейчас при попытке создать модуль в папке, в названии которой встречаются пробелы, модуль создаётся не там, где надо.

**Comment by yurapriv** [comment]
Та же проблема происходит при работе с папками, в названии которых встречаются буквы НЕ латинского алфавита

**Comment by EvgenyIv96** [comment]
Исправлено.

62b0637e382200fd7cf4c5f7ade2da785abe5cbb
